### ISSUE TITLE
Incorrect update plan when changing security groups for VPC instances

### ISSUE THREAD

**Issue by mconigliaro** [sparkleformation/sparkle_formation#160]
When changing security groups for a VPC instance, the update plan incorrectly reports that it's going to replace the instance.

See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-securitygroupids

**Comment by chrisroberts** [comment]
Talked about this a bit in IRC. The crux of the issue is conditional `update_causes` which flags a false positive on resource replacement. Requires mechanism added to resources registry allowing provider specific customized rules (lambda) registered to given resource type that is provided resource state and can apply some logic to return correct result.

**Comment by chrisroberts** [comment]
The actual planner implementation on the sfn side is going to require a few updates for all this to work, but is great prep for the additional planner implementations on their way.

**Comment by chrisroberts** [comment]
New builtin resource implementation completed and is integrated with sfn as of the 3.0 release. Thanks!
