### ISSUE TITLE
AWS credentials profile

### ISSUE THREAD

**Issue by egeland** [sparkleformation/sparkle_formation#183]
I guess this is a question/feature request:

I usually use the `~/.aws/credentials` and `~/.aws/config` way to manage my various AWS profiles, so rather than manually changing all the `AWS_*` env variables, I just set `AWS_PROFILE` and the entries in those files get picked up by all the official SDKs and CLI tools.

Is there support for this in sparkleformation, and if not, would there be scope to add support for it?

**Comment by egeland** [comment]
Oh, I just found another issue in the CLI repo and seems there's an undocumented (at least it's not in the commented file) `aws_profile_name 'MyProfileNameHere'` option you just put into the `.sfn` file, and it just works!

Sorry about this!

**Comment by egeland** [comment]
Reminder to myself:
`aws_profile_name ENV['AWS_PROFILE']` works nicely, too!

**Comment by beirnsi-ls** [comment]
I'm trying to get this working too, but if I only do this:

```
credentials do
   provider :aws
   aws_profile_name ENV['AWS_PROFILE']
end
```

in .sfn, it's still asking me for my aws_access_key_id, with `AWS_PROFILE=dev` being in my environment.

```
# ~/.aws/credentials
[myprof]
aws_access_key_id = xxxx
aws_secret_access_key = yyyyy
```

```
# ~/.aws/config
[profile myprof]
region = eu-central-1

[profile prod]
source_profile = myprof
role_arn = xxxxxxx

[profile dev]
source_profile = myprof
role_arn = xxxxxxx
```

This works for the aws CLI, so I'm pretty sure the credentials and config file are correct. @egeland could elaborate a bit more on how you got this working?

**Comment by chrisroberts** [comment]
@beirnsi-ls Hi! After looking at this for a bit, I can see the problem. The issue is that having the profile name defined in the credentials file and the configuration file causes an overwrite to occur (when it should be a merge). If you have the `region` setting into the credentials file and remove the `[profile myprof]` from the configuration file, it should work as expected. I'll get the file parsing fixed up in the miasma library so this doesn't happen, but for now that should provide you with a workaround.

Cheers!

**Comment by beirnsi-ls** [comment]
Thanks! This allowed me to get it working, but I had to put everything in my .credentials file. Otherwise it still wouldn't work.
