### ISSUE TITLE
How can I reference an object with the variables section of an ARM template?

### ISSUE THREAD

**Issue by russellseymour** [sparkleformation/sparkle_formation#192]
Hello,

I have created a SparkleFormation definition that creates an ARM template with nested variables. 

The code:

``` ruby
variables do
    set!(:name) do

      # Set the storage account name
      set!(:storage_account_name, concat!(parameters!(:prefix), "-", variables!(:unique_short), '-SA'))

    end
end
```

How can I use the `variables!` function to get at the nested object.   I know that this is just a case of getting the syntax correct but I cannot work out what it is.

If I was using an ARM template directly then to get at the nested value I would use

```
variables('name').storageAccountName
```

Indeed I can use the following code in the definition

``` ruby
variables!(:name).storageAccountName
```

And this generates the correct output, however I have to remember to do the conversion from a symbol to a string myself.  Is there anyway of using the symbol of the variable in this context to get the correctly namespaced variable?

Thanks in advance.

**Comment by chrisroberts** [comment]
Hi! The function building implementation doesn't impose casing rules mainly because of the inconsistencies depending on what was being called. I hadn't seen usage like this before, so it wasn't a use case I was looking to cover. I don't have a good work around for this at this point, but I'll get a helper implemented to cover the behavior you're looking for soon.

Cheers!
