### ISSUE TITLE
Passing compile time parameters to --apply-stack

### ISSUE THREAD

**Issue by Typositoire** [sparkleformation/sparkle_formation#198]
I'm currently trying something and I'd like to know if this is actually something possible ?! I can't seem to achieve it.

I have a vpc template that set availability zones (gets them from EC2 API) and i'd like to reuse them in another template, right now I just output them but I can't loop over them as Ref!(), but I could as state!(). 

Thanks!

**Comment by ianrossi** [comment]
Can you share your code with a Gist or something?

**Comment by Typositoire** [comment]
What do you mean share? Is it possible to output compile time attribute as compile time attribute and not as ref!() ? If yes, how would I do that ?

**Comment by chrisroberts** [comment]
Hi. You can output availability zones to use as inputs for other stacks, but they will not work the same way as a compile time parameter because you will only have the runtime functionalities available to interact with the list. I've never had a problem with it, but some people's use cases require them to be much more specific (explicit AZ isolation and such) than I usually build things.

In the network template, you want to output your AZs as a comma delimited list. Then in your other templates that require the AZ list, have a parameter that is a `CommaDelimitedList` type. This gives you a runtime array that you can then use within your templates.

So your output would be something like:

```ruby
outputs.my_azs.value join!(azs!, :options => {:delimiter => ','})
```

and for the input you would structure it like:

```ruby
parameters.my_azs.type 'CommaDelimitedList'
```

**Comment by ianrossi** [comment]
@Typositoire What I meant was, can you share your template code here? Either by pasting or a link to snippet or Github Gist. I'm actually interested in how you're using compile-time parameters. Of course, just asking for a redacted version. Thanks.

**Comment by Typositoire** [comment]
@chrisroberts I can do that, once I got that how can I use the runtime array ?? Doing anything on ref!(:myazs) doesn't work.

@ianrossi Nothing fancy I threw there compile-time params because I knew I could interact with them in ruby. If there's another way it's good.

**Comment by slyness** [comment]
You can reference the value of a compile time parameter using state!(). 

```
Outputs do
	my_fancy_output.value state!(:my_compile_time_parameter)
End
```

**Comment by slyness** [comment]
So to continue.. if you output the value using state of the compile time parameter in your VPC template than you'll be able to consume it using --apply-stack in your new stack template.
