### ISSUE TITLE
How to pass references to dynamics

### ISSUE THREAD

**Issue by jamesla** [sparkleformation/sparkle_formation#223]
In the following example

```
SparkleFormation.new(:test, :provider => :aws) do
  dynamic!(:ec2_vpc, :myVpc)

  dynamic!(:myDynamic, :subnet,
      :vpc_id => ref!(:myVpc_ec2_vpc))
end
```

```
SparkleFormation.dynamic(:myDynamic) do |name, opts={}|
  parameters do
    set!("#{name}_vpc_id".to_sym) do
      type 'String'
      default opts[:vpc_id]
    end
  end

  dynamic!(:ec2_subnet, :mySubnet) do
    properties do
      vpc_id ref!("#{name}_vpc_id")
    end
  end
end
```

Gives me the error:

ERROR: Miasma::Error::ApiError::RequestError: Bad Request - ValidationError: Template format error: Every Default member must be a string.

Anybody know how I can make this work?

**Comment by webframp** [comment]
@jamesla I think this is because in your custom dynamic you've declared the property type to be `String` but you're passing in a value from `ref!` which will never be a plain string value.

In this case you may be better off using the AWS-Specific Parameter Types in your custom dynamic so you could try this instead to define the param:

```rb
  parameters do
    set!("#{name}_vpc_id".to_sym) do
      type 'AWS::EC2::VPC::Id'
      default opts[:vpc_id]
    end
  end
```

Still not sure if this will work if you're passing in `{ "Ref" : "VpcId" }` without trying it out.

**Comment by jamesla** [comment]
Thanks @webframp I have changed the type to 'AWS::EC2::VPC::Id' and am still getting the same error.

Below is the output of sfn print

```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "Sparkle Guide Compute Template",
  "Resources": {
    "MyVpcEc2Vpc": {
      "Type": "AWS::EC2::VPC"
    },
    "MySubnetEc2Subnet": {
      "Type": "AWS::EC2::Subnet",
      "Properties": {
        "VpcId": {
          "Ref": "SubnetVpcId"
        }
      }
    }
  },
  "Parameters": {
    "SubnetVpcId": {
      "Type": "AWS::EC2::VPC::Id",
      "Default": {
        "Ref": "MyVpcEc2Vpc"
      }
    }
  }
}

```

**Comment by chrisroberts** [comment]
In the examples you provide you are creating a VPC with the template. Because the VPC is a resource created at run-time, you cannot have the VPC ID defined within a parameter because the parameters are required before the template is processed. Instead, you want to create the VPC, and then use the reference to the resource to provide the ID. As a flat template, it would look like this:

```ruby
SparkleFormation.new(:network) do
  dynamic!(:ec2_vpc, :my_vpc)
  dynamic!(:ec2_subnet, :subnet) do
    properties do
      vpc_id ref!(:my_vpc_ec2_vpc)
    end
  end
end
```
Now, with some of the DSL features we can make this a little nicer and shorter:

```ruby
SparkleFormation.new(:network) do
  vpc = dynamic!(:ec2_vpc, :my_vpc)
  dynamic!(:ec2_subnet, :subnet.properties.vpc_id ref!(vpc.resource_name!)
end
```
And to take your example and apply the above, you would end up with something kinda like this:

```ruby
SparkleFormation.dynamic(:my_dynamic) do |name, opts={}|
  dynamic!(:ec2_subnet, name) do
    properties do
      vpc_id opts[:vpc_id]
    end
  end
end
```

```ruby
SparkleFormation.new(:test, :provider => :aws) do
  vpc = dynamic!(:ec2_vpc, :my_vpc)

  dynamic!(:my_dynamic, :subnet,
      :vpc_id => ref!(vpc.resource_name!)
end
```
The guide can help walk through some of these things and explain how they work: http://www.sparkleformation.io/docs/guides/getting-started.html#create-a-template

Cheers!
