### ISSUE TITLE
Looping in an "_array"

### ISSUE THREAD

**Issue by rabidscorpio** [sparkleformation/sparkle_formation#55]
I'd like to be able to take a hash and create an _array from that hash, is there a way to do this?  An example would be creating a hash of tags that I want to apply to an instance.  The _array mechanism is very verbose and being able to use a hash would make it much more readable.  Thanks!

**Comment by chrisroberts** [comment]
Hi! The `array!` method is generally less verbose when defining an array of types due to the support of eval'ing proc type objects within the dsl. Thus, you get the benefit of defining something like this:

```ruby
tags array!(
  ->{
    key 'CustomName'
    value 'CustomValue'
  }
)
```

and you automatically get the correct casing scheme applied to keys based on context of the proc type object being eval'ed. There is also the issue where some resource expect different tag types (like ASGs expecting a PropagateAtLaunch key/value pair within the tag hash).

If you have a Hash, containing direct key/value pairs for tags, and want to convert them into an array, you can do so with a bit of Ruby:

```ruby
# Assuming the following:
# my_tags = {'CustomName' => 'CustomValue'}

tags my_tags.map{|k,v| {'Key' => k, 'Value' => v}}
```

Cheers!

**Comment by chrisroberts** [comment]
Closing this up. Please open a new issue if required.
