### ISSUE TITLE
Error  using SparkleFormation::SparklePack.new inside a template

### ISSUE THREAD

**Issue by manell** [sparkleformation/sparkle_formation#82]
I am trying to require a SparklePack from a template. According to the [Docs](http://www.sparkleformation.io/docs/sparkle_formation/sparkle-packs.html),  I need to write something like this:
```
root_pack = SparkleFormation::SparklePack.new(:name => 'my-pack')

sfn = SparkleFormation.new(
  :my_template,
  :sparkle => root_pack
)
```
However, I am getting this error:

```
./cfn/template.rb:3:in `block (3 levels) in templates': uninitialized constant #<Class:0x00000000a56068>::SparkleFormation::SparklePack (NameError)
	from /var/lib/gems/1.9.1/gems/sparkle_formation-1.0.4/lib/sparkle_formation/sparkle.rb:253:in `instance_eval'
	from /var/lib/gems/1.9.1/gems/sparkle_formation-1.0.4/lib/sparkle_formation/sparkle.rb:253:in `block (3 levels) in templates'
	from /var/lib/gems/1.9.1/gems/sparkle_formation-1.0.4/lib/sparkle_formation/sparkle.rb:245:in `glob'
	from /var/lib/gems/1.9.1/gems/sparkle_formation-1.0.4/lib/sparkle_formation/sparkle.rb:245:in `block (2 levels) in templates'
	from /var/lib/gems/1.9.1/gems/sparkle_formation-1.0.4/lib/sparkle_formation/sparkle.rb:244:in `tap'
	from /var/lib/gems/1.9.1/gems/sparkle_formation-1.0.4/lib/sparkle_formation/sparkle.rb:244:in `block in templates'
	from /var/lib/gems/1.9.1/gems/bogo-0.1.30/lib/bogo/memoization.rb:60:in `memoize'
	from /var/lib/gems/1.9.1/gems/sparkle_formation-1.0.4/lib/sparkle_formation/sparkle.rb:243:in `templates'
	from /var/lib/gems/1.9.1/gems/sparkle_formation-1.0.4/lib/sparkle_formation/sparkle.rb:283:in `get'
	from /var/lib/gems/1.9.1/gems/sparkle_formation-1.0.4/lib/sparkle_formation/sparkle_formation.rb:98:in `compile'
	from parse_instance.rb:12:in `<main>'
```

Trying to find out what was wrong, I end up on this code  [part](https://github.com/sparkleformation/sparkle_formation/blob/master/lib/sparkle_formation/sparkle.rb#L64) . If I didn't misunderstand the code, that function basically is creating an empty object with a ```SparkleFormation``` class, and then is copying some constants.
The class ```SparklePack``` is not being defined, so how can I get access to ```SparkleFormation::SparklePack``` ?

The following hack helps me to skip this problem.
```
root_pack = ::SparkleFormation::SparklePack.new(:name => 'my-pack')

sfn = SparkleFormation.new(
  :my_template,
  :sparkle => root_pack
)
```
But then I came across with another error related to the option ```:sparkle => root_pack```.  According to this [code](https://github.com/sparkleformation/sparkle_formation/blob/master/lib/sparkle_formation/sparkle_formation.rb#L324)  I feel that the option parameter should be ``` :sparkle_path```  which is expecting a path and not a ```SparkleFormation::Sparkle```.

So in the end, this is the code that works for me.
```
root_pack = ::SparkleFormation::SparklePack.new(:name => 'my-pack')

sfn = SparkleFormation.new(
  :my_template
)

sfn.sparkle.add_sparkle(root_pack)
```

There are a lot of chances that I have missunderstood something, but I don't know what.

**Comment by chrisroberts** [comment]
Hi! Can you provide some context on what your use case is and what is the expected outcome? That should help to provide the correct response. Thanks!

**Comment by manell** [comment]
Well, I have a SparkleFormation collection that I want to instantiate in many other projects. To do so, I have packaged the collection in a gem, so that I can require this gem in other projects.
The project that builds the gem has this layout.
```
> tree
.
|____devops-pack.gemspec
|____lib
| |____sparkleformation
| | |____dynamics
| | |____components
| | |____registry
| |____devops-pack.rb
```

This is the code to register the gem. I have some troubles calling the function register without any parameter, so in the end I have to call the function with a name and a path.
```
path =  File.join(File.dirname(__FILE__), "sparkleformation")
SparkleFormation::SparklePack.register! "devops-pack",  path
```
On the other hand, I have the projects where I want to build the templates. They follow this layout.
```
.
|____parser.rb
|____cfn
  |____template.rb
```

The file parser.rb contains the following code.
```
require 'sparkle_formation'
require 'pp'
require 'json'

SparkleFormation.sparkle_path = File.join(File.dirname(__FILE__), 'cfn')

puts JSON.pretty_generate(
  SparkleFormation.compile(
    File.join(
      File.dirname(__FILE__),
      'cfn/template.rb'
    )
  )
)

```
And the template.rb file contains this code.
```
require "devops-pack"

root_pack = ::SparkleFormation::SparklePack.new(:name => 'devops-pack')

sfn = SparkleFormation.new(:trustedx) do
  *** require some dynamics here ***
end

sfn.sparkle.add_sparkle(root_pack)
sfn.load(:common)
```
The code is working, however, according to the docs this one should work too. But it doesn't because of the problems cited in the previous post. 
```
require "devops-pack"

root_pack = SparkleFormation::SparklePack.new(:name => 'devops-pack')

sfn = SparkleFormation.new(:trustedx, :sparkle => root_pack).load(:common) do
  *** require some dynamics here ***
end

```

**Comment by chrisroberts** [comment]
Okay, the only other question I have is: are you using `sfn`?

**Comment by manell** [comment]
No, I run ```$ ruby parser.rb``` to compile the code.

**Comment by chrisroberts** [comment]
Sorry for all the questions, but I just wanted to make sure I had the correct context for the question so I wasn't giving you an answer that wasn't applicable. 

This is definitely something that needs to be addressed in the documentation. The reason why the former example you posted works, and the latter example does not has to do with how the files are being evaluated. The template files located within a pack (including the local (root) pack) are pre-loaded via a customized module that generates the actual pack, which can then be used later when templates are compiled. The customized module provides stubs to internals providing just enough compatibility to allow everything to be loaded. This stubbing behavior is why you find the requirement to use explicit namespacing (`::SparkleFormation`) to make the pack class accessible. So this is the reason _why_ you are seeing this behavior.

Now because you are using the library directly and not the implementation (`sfn`) you have to provide some setup in your `parser.rb` that `sfn` does via configuration around the packs. For the local templates you have defined in your project, they should never have to deal with or worry about the packs. It's the thing you run to actually generate the template output that cares about the packs. Using `sfn` to generate your templates will likely be much easier to access the different features of the library (as it is the reference implementation of the library), but you can do it directly:

```ruby
require 'sparkle_formation'
require 'pp'
require 'json'
require "devops-pack"

SparkleFormation.sparkle_path = File.join(File.dirname(__FILE__), 'cfn')
devops_pack = SparkleFormation::SparklePack.new(:name => 'devops-pack')

sparkle_template = SparkleFormation.compile(:instance, :sparkle)
sparkle_template.sparkle.add_sparkle(devops_pack)

puts JSON.pretty_generate(sparkle_template.compile)
```

_NOTE: I haven't tested the above code but it's the basic idea._

You don't want to modify the root pack, because the local project pack should be your root pack. So you'll just want to add the devops pack in, and then compile the instance. You'll notice a couple changes as well on the `SparkleFormation.compile` call. First is that we can just provide it the name of the template we want to load. The second is the `:sparkle` option. This will return back a `SparkleFormation` instance instead of dumping a `Hash`. With the instance, new packs can be added, and then it can be compiled to make use of any added packs.

You can also have a look at how `sfn` handles this here:

https://github.com/sparkleformation/sfn/blob/ce7df1e24c01f50e1b6e3097696024fb8f027b67/lib/sfn/command_module/template.rb#L65-L68

If you don't have any specific reasons for not using `sfn`, it will likely be a bit easier as it has support for these things, and provides a handy `print` command to output the JSON contents. Otherwise I hope this will help get your parser script going. Please let me know if you're still having problems.

Cheers!

**Comment by manell** [comment]
I'll use the sfn tool. 
Thanks for your time!
